using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ElectionTactics
{
    public static class PartyNameGenerator
    {
        private static string GeneratedNameTemplate = "<GENERATED>"; // Special template that is replaced with a name generated by the district name generator.

        private static Dictionary<string, int> Adjectives = new() // A
        {
            { GeneratedNameTemplate, 200 },
            { "Revolutionary", 100 },
            { "Socialist", 100 },
            { "Anarchist", 100 },
            { "Conservative", 100 },
            { "Fascist", 100 },
            { "National", 100 },
            { "Nationalist", 100 },
            { "International", 100 },
            { "Social", 100 },
            { "Democratic", 100 },
            { "Social Democratic", 100 },
            { "Communist", 100 },
            { "Republican", 100 },
            { "Communal", 100 },
            { "Progressive", 100 },
            { "Liberal", 100 },
            { "Libertarian", 100 },
            { "United", 100 },
            { "Eastern", 100 },
            { "Western", 100 },
            { "Northern", 100 },
            { "Southern", 100 },
            { "Radical", 100 },
            { "Red", 100 },
            { "Black", 100 },
            { "Blue", 100 },
            { "Yellow", 100 },
            { "Green", 100 },
            { "Orange", 100 },
            { "White", 100 },
            { "Purple", 100 },
            { "Pink", 100 },
            { "Brown", 100 },
            { "Crimson", 100 },
            { "Teal", 50 },
            { "Reformist", 100 },
            { "Capitalist", 100 },
            { "Anti-Capitalist", 100 },
            { "Holy", 100 },
            { "Centrist", 100 },
            { "Populist", 100 },
            { "Federalist", 100 },
            { "Conservationist", 100 },
            { "Marxist", 100 },
            { "Free", 100 },
            { "Individualist", 100 },
            { "Collectivist", 100 },
            { "Queer", 100 },
            { "Imperialist", 100 },
            { "Maoist", 100 },
            { "Great", 100 },
            { "Greater", 100 },
            { "Environmentalist", 100 },
            { "Agrarian", 100 },
            { "New", 100 },
            { "Committed", 100 },
            { "Humanist", 100 },
            { "Civil", 100 },
            { "Alternative", 100 },
            { "Public", 100 },
            { "Federal", 100 },
            { "Traditional", 100 },
            { "Constitutional", 100 },
            { "Patriotic", 100 },
            { "Collective", 100 },
            { "Cooperative", 100 },
            { "Common", 100 },
            { "Rational", 100 },
            { "Scientific", 100 },
            { "Unified", 100 },
            { "Technocratic", 100 },
            { "Supreme", 100 },
            { "Nationalized", 100 },


            { "Mega", 60 },
            { "Super", 60 },

            { "Evil", 50 },
            { "First", 50 },
            { "Second", 50 },
            { "Third", 50 },
            { "Last", 50 },
            { "Ultimate", 50 },
            { "Final", 50 },
            { "Sovereign", 50 },
            { "Central", 50 },
            { "Radiant", 50 },
            { "Perfect", 50 },
            { "Compassionate", 50 },
            { "Benevolent", 50 },
            { "Approved", 50 },

            { "Villainous", 30 },
            { "Correct", 30 },
            { "Acceptable", 30 },
        };

        private static Dictionary<string, int> PartyTypeNouns = new() // T
        {
            { GeneratedNameTemplate, 200 },
            { "People's", 100 },
            { "Workers'", 100 },
            { "Patriot", 100 },
            { "Common Man's", 100 },
            { "Constitution", 100 },
            { "Elite", 100 },
            { "Mass", 100 },
            { "Niche", 100 },
            { "Civilian", 100 },
            { "Youth", 100 },
            { "Women's", 100 },
            { "Men's", 100 },
            { "Corporate", 100 },
            { "Occupation", 100 },
            { "Rebel", 100 },
            { "Senior", 100 },
            { "Junior", 100 },
            { "Oligarch", 100 },
            { "Monarch", 100 },
            { "Forces", 100 },
            { "Civic", 100 },
            { "Republicans", 100 },
            { "Greens", 100 },
            { "Centre", 100 },
            { "One", 100 },
            { "Reforms", 100 },
            { "Forward", 100 },
            { "Cause", 100 },
            { "Citizen", 100 },
            { "Values", 100 },
            { "Systems", 100 },
            { "Human", 100 },
            { "Tomorrow", 100 },
            { "First", 100 },
            { "Executive", 100 },
        };

        private static Dictionary<string, int> PartyPurposeWords = new() // U
        {
            { GeneratedNameTemplate, 250 },
            { "Justice", 100 },
            { "Peace", 100 },
            { "Resurgence", 100 },
            { "Order", 100 },
            { "Law", 100 },
            { "Freedom", 100 },
            { "Liberty", 100 },
            { "Development", 100 },
            { "Liberation", 100 },
            { "Salvation", 100 },
            { "Science", 100 },
            { "Thought", 100 },
            { "Equality", 100 },
            { "Equity", 100 },
            { "Anarchy", 100 },
            { "Integration", 100 },
            { "Unity", 100 },
            { "Human Rights", 100 },
            { "Opportunity", 100 },
            { "Future", 100 },
            { "Society", 100 },
            { "Independence", 100 },
            { "Renewal", 100 },
            { "Production", 100 },
            { "Labour", 100 },
            { "Homeland", 100 },
            { "Motherland", 100 },
            { "Regeneration", 100 },
            { "Mobilization", 100 },
            { "Honor", 100 },
            { "Solidarity", 100 },
            { "Enlightenment", 100 },
            { "Democracy", 100 },
            { "Community", 100 },
            { "Cooperation", 100 },
            { "Prosperity", 100 },
            { "Stability", 100 },
            { "Tradition", 100 },
            { "Continuity", 100 },
            { "Progress", 100 },
            { "Wealth", 100 },
            { "Horizon", 100 },
            { "Optimization", 100 },
            { "Dominion", 100 },
            { "Victory", 100 },
            { "Everything", 100 },
            { "Glory", 100 },

            { "Hope", 70 },
            { "Grace", 70 },
            { "Faith", 70 },
            { "Wisdom", 70 },
            { "Truth", 70 },
            { "Efficiency", 70 },

            { "Harmony", 50 },
            { "Love", 50 },
            { "Compassion", 50 },
            { "Empathy", 50 },
            { "Togetherness", 50 },
            { "Friendship", 50 },
            { "Affection", 50 },
            { "Serenity", 50 },
            { "Fulfillment", 50 },
            { "Balance", 50 },
            { "Cohesion", 50 },
            { "Resonance", 50 },
            { "Concord", 50 },
            { "Accord", 50 },
            { "Heritage", 50 },
            { "Family", 50 },
            { "Happiness", 50 },

            { "Tyranny", 40 },
            { "Purity", 40 },
            { "Obedience", 40 },
            { "Iron", 40 },
            { "Steel", 40 },
            { "Disco", 40 },
            { "Party", 40 },
            { "Blood", 40 },

            { "Fellowship", 30 },
            { "Calm", 30 },
            { "Contentment", 30 },
            { "Tranquility", 30 },
            { "Joy", 30 },
            { "Bliss", 30 },
            { "Ease", 30 },
            { "Alignment", 30 },
            { "Symmetry", 30 },
            { "Understanding", 30 },
            { "Flow", 30 },
            { "Spirit", 30 },
            { "Soul", 30 },
            { "Goodwill", 30 },
            { "Ascension", 30 },
            { "Cleansing", 30 },

            { "Brotherhood", 30 },
            { "Sisterhood", 30 },
        };

        private static Dictionary<string, int> PartyNouns = new() // P
        {
            { "Party", 500 },

            { "Movement", 200 },
            { "Front", 150 },
            { "Union", 150 },

            { "League", 100 },
            { "Alliance", 100 },
            { "Action", 100 },
            { "Organisation", 100 },
            { "Association", 100 },
            { "Treaty", 100 },
            { "Pact", 100 },
            { "Bloc", 100 },
            { "Federation", 100 },
            { "Coalition", 100 },
            { "Faction", 100 },
            { "Militia", 100 },
            { "Cartel", 100 },
            { "Council", 100 },
            { "Democrats", 100 },
            { "Generation", 100 },
            { "Citizens", 100 },
            { "Nation", 100 },
            { "Voice", 100 },
            { "Network", 100 },
            { "Forum", 100 },
            { "Initiative", 100 },
            { "Assembly", 100 },
            { "Collective", 100 },
            { "Advancement", 100 },

            { "Tribune", 50 },
            { "Tigers", 50 },
            { "Panthers", 50 },
            { "Lions", 50 },
            { "Dawn", 50 },
            { "Guard", 50 },
            { "Proposal", 50 },
            { "Contract", 50 },
            { "Directorate", 50 },
            { "Authority", 50 },
            { "Ministry", 50 },
            { "Department", 50 },
            { "Mandate", 50 },
            { "Vanguard", 50 },
            { "Legion", 50 },
            { "Path", 50 },
            { "Committee", 50 },

            { "Algorithm", 20 },
            { "Will", 20 },
            { "Purpose", 20 },
            { "Doctrine", 20 },
            { "Alignment", 20 },
            { "Keepers", 20 },
        };

        private static Dictionary<string, int> Prepositions = new() // f
        {
            { "of", 100 },
            { "for", 100 },
            { "for the", 40 },
            { "through", 20 },
            { "beyond", 8 },
            { "over", 8 },
        };


        private static Dictionary<string, int> And = new Dictionary<string, int>() { { "and", 100 } }; // &
        private static Dictionary<string, int> The = new Dictionary<string, int>() { { "The", 100 } }; // t

        private static Dictionary<char, Dictionary<string, int>> ListDict = new Dictionary<char, Dictionary<string, int>>()
        {
            {'A', Adjectives },
            {'T', PartyTypeNouns },
            {'P', PartyNouns },
            {'U', PartyPurposeWords },
            {'f', Prepositions },
            {'&', And },
            {'t', The },
        };

        /// <summary>
        /// This list defines which combinations of the above lists are allowed and with which probabilities they can appear.
        /// </summary>
        private static Dictionary<string, int> NameLanguage = new Dictionary<string, int>()
        {
            // Doubles
            { "AP", 150 },
            { "TP", 80 },
            { "UP", 150 },
            { "AU", 120 },
            { "UU", 35 },

            { "PfU", 80 },
            { "U&U", 50 },
            { "A&A", 25 },

            { "tP", 10 },

            // Triples
            { "ATP", 70 },
            { "AUP", 90 },
            { "TUP", 70 },
            { "TAP", 40 },
            { "AAP", 50 },

            { "APfU", 60 },
            { "PfAU", 60 },
            { "TPfU", 50 },
            { "UPfU", 50 },
            { "U&UP", 40 },
            { "AAUP", 20 },

            { "tAP", 10 },
            { "tTP", 10 },
            { "tUP", 10 },
            { "tPfU", 10 },

            // Fourlets
            { "ATUP", 50 },

            // Special misc
            { "PfU&U", 50 },
            { "PfUfU", 10 },
            { "PfU,U&U", 20 },
            { "U,U&UP", 20 },
            { "UfUP", 20 },
            { "APfAU", 20 },
        };

        private static List<Color> Colors = new List<Color>()
        {
            new Color(0.90f, 0.30f, 0.55f), // 0 - Pink
            new Color(0.00f, 0.50f, 0.00f), // 1 - Green
            new Color(0.10f, 0.40f, 0.90f), // 2 - Blue
            new Color(0.85f, 0.05f, 0.05f), // 3 - Red
            new Color(0.80f, 0.75f, 0.15f), // 4 - Yellow
            new Color(0.10f, 0.10f, 0.10f), // 5 - Black
            new Color(0.85f, 0.60f, 0.16f), // 6 - Orange
            new Color(0.80f, 0.00f, 0.80f), // 7 - Purple
            new Color(0.66f, 0.32f, 0.10f), // 8 - Brown
            new Color(0.00f, 0.80f, 0.90f), // 9 - Light Blue
            new Color(0.00f, 0.90f, 0.00f), // 10 - Light Green
            new Color(0.00f, 0.65f, 0.60f), // 11 - Teal
            new Color(0.45f, 0.00f, 0.05f), // 12 - Crimson
        };


        public static string GetRandomPartyName(int maxLength = 32, bool log = true)
        {
            string name = "";

            string nameType = NameLanguage.GetWeightedRandomElement();
            foreach (char c in nameType)
            {
                if (c == ',')
                {
                    name = name.TrimEnd(' ');
                    name += ", ";
                }

                else if (ListDict.ContainsKey(c))
                {
                    Dictionary<string, int> list = ListDict[c];
                    string word = GetRandomWord(name, list);

                    // If word is the template for a randomly generated name, generate a name and use it as the word
                    if (word == GeneratedNameTemplate)
                    {
                        word = ElectionTacticsGame.Instance.GetRandomDistrictName();
                        word = word.Trim();
                        if (log) Debug.Log($"Generated name '{word}' for party name template.");
                    }

                    // Add resolved word to the name
                    name += word + " ";
                }

                else throw new System.Exception($"Character {c} is not handled in party name generation language.");
            }
            name = name.Trim(' ');

            if (maxLength > 0 && maxLength < 16)
            {
                maxLength = 0;
                Debug.LogWarning($"maxLength is getting ignored because it was below 16. Too dangerous to not find any names.");
            }
            while (maxLength > 0 && name.Length > maxLength) name = GetRandomPartyName(log: false);

            if (log) Debug.Log($"Generated party name '{name}' out of language word '{nameType}'.");
            return name;
        }

        public static Color GetPartyColor(string partyName, List<Color> alreadyTaken)
        {
            if (partyName.Contains("Pink") && !alreadyTaken.Contains(Colors[0])) return Colors[0];
            if (partyName.Contains("Green") && !alreadyTaken.Contains(Colors[1])) return Colors[1];
            if (partyName.Contains("Blue") && !alreadyTaken.Contains(Colors[2])) return Colors[2];
            if (partyName.Contains("Red") && !alreadyTaken.Contains(Colors[3])) return Colors[3];
            if (partyName.Contains("Yellow") && !alreadyTaken.Contains(Colors[4])) return Colors[4];
            if (partyName.Contains("Black") && !alreadyTaken.Contains(Colors[5])) return Colors[5];
            if (partyName.Contains("Orange") && !alreadyTaken.Contains(Colors[6])) return Colors[6];
            if (partyName.Contains("Purple") && !alreadyTaken.Contains(Colors[7])) return Colors[7];
            if (partyName.Contains("Brown") && !alreadyTaken.Contains(Colors[8])) return Colors[8];
            if (partyName.Contains("Teal") && !alreadyTaken.Contains(Colors[8])) return Colors[11];
            if (partyName.Contains("Crimson") && !alreadyTaken.Contains(Colors[8])) return Colors[12];
            else return GetRandomColor(alreadyTaken);
        }

        public static Color GetRandomColor(List<Color> forbiddenColors, Color? oldColor = null)
        {
            // Check if we have run out of unique colors
            if (forbiddenColors.Count >= Colors.Count)
            {
                Debug.LogWarning("All party colors taken! Returning white as fallback.");
                return Color.white;
            }

            // Return next available color in list from oldColor
            if (oldColor != null)
            {
                Color newColor = Color.white;
                int id = Colors.IndexOf(oldColor.Value);
                do
                {
                    id++;
                    if (id >= Colors.Count) id = 0;
                    newColor = Colors[id];
                } while (forbiddenColors.Contains(newColor));
                return newColor;
            }

            // Return random color if no old color set
            else
            {
                Color c = Colors.RandomElement();
                while (forbiddenColors.Contains(c))
                {
                    c = Colors.RandomElement();
                }
                return c;
            }
        }
        public static Color GetRandomColorBackward(List<Color> forbiddenColors, Color? oldColor = null)
        {
            if (forbiddenColors.Count >= Colors.Count)
                return Color.white;

            if (oldColor != null)
            {
                int id = Colors.IndexOf(oldColor.Value);
                Color newColor;
                do
                {
                    id--;
                    if (id < 0) id = Colors.Count - 1;
                    newColor = Colors[id];
                } while (forbiddenColors.Contains(newColor));
                return newColor;
            }

            Color c = Colors.RandomElement();
            while (forbiddenColors.Contains(c)) c = Colors.RandomElement();
            return c;
        }

        public static Color GetDefaultPlayerColor() => Colors[10];

        private static string GetRandomWord(string partyName, Dictionary<string, int> wordList)
        {
            string word = wordList.GetWeightedRandomElement();
            int numTries = 0;
            while (partyName.Contains(word) && numTries <= 20)
            {
                word = wordList.GetWeightedRandomElement();
                numTries++;
            }
            return word;
        }

        public static string CreateAcronym(string partyName)
        {
            if (partyName.Length <= 5) return partyName;

            // Acronym is first letter of each capitalized word
            string acronym = "";
            foreach (string word in partyName.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                if (char.IsUpper(word[0])) acronym += word[0];
                else if (word == "and") acronym += "&";
            }

            // If acronym is empty, consider lower case words
            if (acronym == "")
            {
                foreach (string word in partyName.Split(' ', StringSplitOptions.RemoveEmptyEntries))
                {
                    acronym += word[0];
                }
            }

            return acronym;
        }
    }
}
